name: Build obsidian plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: Keyboard-Formatter # Change this to the name of your plugin-id folder

jobs:
  build:
    runs-on: ubuntu-latest

    # Required so GITHUB_TOKEN is allowed to create the release and upload assets
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x" # Using the latest LTS from https://nodejs.org/en/about/previous-releases
      - name: Build
        run: |
          yarn
          yarn run build --if-present
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip ${{ env.PLUGIN_NAME }}
          ls
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          # Release name and tag default to the pushed tag (e.g. 1.2.3)
          draft: false
          prerelease: false
          files: |
            ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
            main.js
            manifest.json
            styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
